services:
  knot:
    image: atcr.io/cove.town/knot:latest
    pull_policy: always
    restart: always
    ports:
      - "22:2222"
    environment:
      - KNOT_MASTER_KEY=${KNOT_MASTER_KEY}
      - KNOT_HOSTNAME=${KNOT_HOSTNAME}
      - KNOT_ADMINS=${KNOT_ADMINS}
    volumes:
      - ./config.toml:/etc/knot/config.toml:ro
      - knot_data:/data
    labels:
      - observability.enable=true
      - observability.service=knot

volumes:
  knot_data:
