services:
  pds:
    build:
      context: https://tangled.org/tranquil.farm/tranquil-pds.git#main
      args:
        DISTROLESS_IMAGE: gcr.io/distroless/cc-debian13:latest@sha256:a017e74bd2a12d98342dbecd33d121d2b160415ed777573dc1808969e989d94d
    restart: always
    env_file:
      - .env
    environment:
      - "SERVER_HOST=[::]"
      - PDS_HOSTNAME=pds.cove.town
      - PDS_USER_HANDLE_DOMAINS=cove.town
      - PDS_BANNED_WORDS=knot,spindle,hold,atcr,s3,garage,www,mail,deploy
      - INVITE_CODE_REQUIRED=true
      - DISABLE_ACCOUNT_VERIFICATION_GATE=true
      - CRAWLERS=https://bsky.network
    volumes:
      - blob_data:/var/lib/tranquil-pds/blobs
      - store_data:/var/lib/tranquil-pds/store
    networks:
      - default
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.pds-handles.rule=HostRegexp(`^.+\.cove\.town$`)
      - traefik.http.routers.pds-handles.entrypoints=websecure
      - traefik.http.routers.pds-handles.priority=1
      - traefik.http.routers.pds-handles.tls=true
      - traefik.http.routers.pds-handles.service=pds-handles
      - traefik.http.services.pds-handles.loadbalancer.server.port=3000

volumes:
  blob_data:
  store_data:

networks:
  dokploy-network:
    external: true
